In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
.jp-Cell { width: 90% !important; margin: 0 auto; }
</style>
"""))

# Introduction to NumPy

### Recap: Python Lists are a container for arbitrary data
Data is accessed by *index*, with the index starting with 0.

In [2]:
# Create a list with arbitrary data
my_list = [1, 'hello', True, 3.14]

# Accessing the data in the list
print("my_list[0] gives:", my_list[0])
print("my_list[1] gives:", my_list[1])
print("my_list[2] gives:", my_list[2])
print("my_list[3] gives:", my_list[3])

my_list[0] gives: 1
my_list[1] gives: hello
my_list[2] gives: True
my_list[3] gives: 3.14


#### You can count from the back with negative indicees and get a slice using the colon

In [3]:
my_list = [1, 'hello', True, 3.14]

# Accessing the data in the list using negative index
print("my_list[-1] gives:",  my_list[-1])

# Slicing the list
print("my_list[1:3] gives:", my_list[1:3])  # Output: ['hello', True]


my_list[-1] gives: 3.14
my_list[1:3] gives: ['hello', True]


#### Lists are mutable: You can also modify the data by index

In [4]:
my_list = [1, 'hello', True, 3.14]

# Modifying the data in the list
my_list[0] = 2
print("my_list after modification:", my_list)


my_list after modification: [2, 'hello', True, 3.14]


#### NumPy Arrays: Key Features

- Homogeneous: Only contain elements of the same data type.
- Fixed Size: Size cannot be changed once created.
- Memory-Efficient: More efficient than Python lists.
- Vectorized Operations: Perform operations on entire arrays at once.
- Multidimensional: Efficiently store and manipulate multi-dimensional data.
- Built-in Functions: Ease mathematical operations and data manipulation.


#### We use NumPy by importing it

Typically we use the alias `np`, as projects tend to use numpy a lot.

In [5]:
import numpy as np

We can now access anything in numpy via np.function

In [6]:
np.pi

3.141592653589793

#### We can create NumPy arrays from lists

In [7]:
my_list = [1.0, 2.0, 3.0, 4.0, 5.0]
my_array = np.array(my_list)

The object type is a numpy array. The type of contained data is dependent on the content

In [8]:
type(my_array), my_array.dtype

(numpy.ndarray, dtype('float64'))

Show that you can change the data type of member of the array to cast to float instead

If a single string is present, everything will be cast into a string! In general, you should already input homogeneous lists

In [9]:
mixed_array = np.array([1, 2, 3, 4, 'hello'])
mixed_array.dtype, mixed_array[0]

(dtype('<U11'), '1')

#### We can also read NumPy arrays from disk
For this first step we will use a set of bond lengths determined by X-ray diffraction. Let us have a look at the first lines of the file. 

In [10]:
data1_path = 'data/bond_lengths.txt'
with open(data1_path, 'r') as fobj:
    lines = fobj.readlines()

for index, line in enumerate(lines):
    print(line.strip())
    if index > 3:
        break

Si  C   2.3048
Si  C   2.3093
Si  C   2.3465
Si  C   2.3929
Si  C   2.4052


In this section explain: Opening files in python. Control statements including the for loop, if statement and break. End on the statement that we have different data types!

#### Let us now load the data using NumPy
Because we have different data types in the lines we need to specify this. We load every column separately into a new variable

In [11]:
element1, element2, length = np.loadtxt(data1_path, dtype='<U11,<U11,float64', unpack=True)

In this section: Revise element unpacking, and function arguments.

#### Let us have a look at the NumPy datatypes:

| Python| NumPy      | Numpy Short |
|-------|------------|-------------|
| float | float64    |   f64       |
| int   | int64      |   i64       |
| bool  | bool       |   b1        |
|complex| complex128 |   c16       |
| str   | str_       |  <U11       |

A list of all data types can be accessed with

In [12]:
 np.sctypeDict.keys()

dict_keys(['?', 0, 'byte', 'b', 1, 'ubyte', 'B', 2, 'short', 'h', 3, 'ushort', 'H', 4, 'i', 5, 'uint', 'I', 6, 'intp', 'p', 9, 'uintp', 'P', 10, 'long', 'l', 7, 'ulong', 'L', 8, 'longlong', 'q', 'ulonglong', 'Q', 'half', 'e', 23, 'f', 11, 'double', 'd', 12, 'longdouble', 'g', 13, 'cfloat', 'F', 14, 'cdouble', 'D', 15, 'clongdouble', 'G', 16, 'O', 17, 'S', 18, 'unicode', 'U', 19, 'void', 'V', 20, 'M', 21, 'm', 22, 'b1', 'bool8', 'i8', 'int64', 'u8', 'uint64', 'f2', 'float16', 'f4', 'float32', 'f8', 'float64', 'c8', 'complex64', 'c16', 'complex128', 'object0', 'bytes0', 'str0', 'void0', 'M8', 'datetime64', 'm8', 'timedelta64', 'int32', 'i4', 'uint32', 'u4', 'int16', 'i2', 'uint16', 'u2', 'int8', 'i1', 'uint8', 'u1', 'complex_', 'single', 'csingle', 'singlecomplex', 'float_', 'intc', 'uintc', 'int_', 'longfloat', 'clongfloat', 'longcomplex', 'bool_', 'bytes_', 'string_', 'str_', 'unicode_', 'object_', 'int', 'float', 'complex', 'bool', 'object', 'str', 'bytes', 'a', 'int0', 'uint0'])

#### Let us determine the mean bond length and its standard deviation
For this we can use NumPys build-in functions. The full list can be found in the routines section of the [NumPy documentation](https://numpy.org/doc/stable/reference/routines.html). Specifically under [statistics](https://numpy.org/doc/stable/reference/routines.statistics.html).

In [13]:
print(np.mean(length), np.std(length))

1.2838740112994351 0.4283874266912911


#### NumPy supports more sophisticated slicing than python lists

In [14]:
length[:5]

array([2.3048, 2.3093, 2.3465, 2.3929, 2.4052])

In [15]:
indexes = [2, 3, 5, 7, 22]
length[indexes]

array([2.3465, 2.3929, 2.4275, 1.418 , 0.98  ])

#### We can create conditional selections with masks
A mask is an array of booleans that has the same size as the array we want to apply the mask to

In [16]:
mask = element1 == 'Si'
mask[2:8]

array([ True,  True,  True,  True, False, False])

In [17]:
length[mask]

array([2.3048, 2.3093, 2.3465, 2.3929, 2.4052, 2.4275, 2.3399, 2.3629,
       2.3749, 2.3862, 2.421 , 2.4355, 2.3087, 2.3309, 2.3411, 2.3701,
       2.4327, 2.4346])

very often you would not store the mask in a variable

In [18]:
length[element1 == 'Si']

array([2.3048, 2.3093, 2.3465, 2.3929, 2.4052, 2.4275, 2.3399, 2.3629,
       2.3749, 2.3862, 2.421 , 2.4355, 2.3087, 2.3309, 2.3411, 2.3701,
       2.4327, 2.4346])

#### Let us calculate means and standard deviations of different bond types
We will use the [logical operations](https://numpy.org/doc/stable/reference/routines.logic.html#logical-operations) for this purpose. `np.logical_and(arr1, arr2)` can be used to get the elementwise truth of "arr1 and arr2"

In [19]:
# np.logical_and can be used to get the elementwise truth of "arr1 and arr2"
# C-C bonds
cc_mask = np.logical_and(element1 == 'C', element2 == 'C')
np.mean(length[cc_mask]), np.std(length[cc_mask])

(1.45835, 0.041565941586832855)

In [20]:
ch_mask = np.logical_and(element1 == 'C', element2 == 'H')
np.mean(length[ch_mask]), np.std(length[ch_mask])

(0.9800000000000004, 4.440892098500626e-16)

In [21]:
(element1 == 'C') & (element2 == 'H');

#### Numpy arrays can be multidimensional.

In [22]:
mult = np.array([[1,2,3], [4,5,6], [7,8,9]])
mult

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# second row or third column
mult[1,:], mult[:,2]

(array([4, 5, 6]), array([3, 6, 9]))

In [24]:
# we can also use this for assignment
mult[1, :] = 0
mult

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

Explain that this is a view of the original data and not a new object in memory

#### We can change the arrangement with reshape

In [33]:
numbers = np.linspace(0.0, 1.0, 12)
numbers

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [34]:
np.reshape(numbers, (4,3))

array([[0.        , 0.09090909, 0.18181818],
       [0.27272727, 0.36363636, 0.45454545],
       [0.54545455, 0.63636364, 0.72727273],
       [0.81818182, 0.90909091, 1.        ]])

### Calculating with NumPy arrays, Basic arithmetic
let us load a new dataset. This time we skip the first column, which contains the atom type and only load the coordinates. Because all loaded data columns have the same type, NumPy will automatically detect the type correctly.

In [35]:
coordinates = np.loadtxt('data/molecule1.xyz', usecols=(1,2,3))
coordinates.shape, coordinates.dtype

((51, 3), dtype('float64'))

Mathematical operations are calculated elementwise. Here we take the difference between to points

In [36]:
coordinates[0] - coordinates[1]

array([-1.477886,  0.42672 , -2.043088])

The distance is the norm of that vector

In [37]:
np.linalg.norm(coordinates[0] - coordinates[1])

2.5574294835126925